# Base config file which stores the default parameters which apply to all model configurations
---

# Mode to use for debugging/development; this only uses a few samples in in the train/val dataset
# to quickly run the code
debug_mode: False

# Root directory of your project; type "pwd" in the command line to find it
root_dir: "/home/bselee/programming/detectors"

input_data: "data/input.txt"

# Base directory for output files; do not change this 
output_path: "output"

# Experiment name; this will be used for the output directory; use "development" when developing
exp_name: "development"

# Name of dataset; must be one of the names in the dataset_map dict
dataset_name: "CocoDetectionMiniTrain"

# Parameters for the dataset class
dataset:

  # Path to the root of the dataset
  root: "/mnt/c/Users/bsele/Documents/Datasets/coco_minitrain_25k"

train:

  optimizer: "adam"
  scheduler: "step_lr"

  batch_size: 4
  learning_rate: 0.001 #1e-3
  weight_decay: 0.0001
  lr_drop: 200

  # Various epochs used during training
  epochs:

    # The epoch to start on; starting at 1 makes calculations for logging and checkpointing more intuitive
    start_epoch: 1
    epochs: 50

    # Number of epochs to checkpoint after; use 'null' to turn off checkpointing
    ckpt_every: 10

validation:
  batch_size: 2

# GPU parameters
cuda:

  # List of GPU devices to use
  gpus: [0]

  num_workers: 0

# Logging parameters
logging:

  # Log the train progress every n steps
  train_steps_freq: 20

# Reproducibility information
reproducibility:
  seed: 42


