# Base config file which stores the default parameters which apply to all model configurations
---

# Whether to run in development/debugging mode; this only uses a few samples in in the train/val dataset
# to quickly run the code as well as sets num_workers=0
dev_mode: True

# Base directory for output files; do not change this 
output_dir: "output/test"

# Experiment name; this will be used for the output directory; use "development" when developing
exp_name: "development"

# Name of dataset; must be one of the names in the dataset_map dict
dataset_name: "CocoDetection"

# Whether to plot the predicted bounding boxes on the test set; if False only the AP scores are shown
plot_detections: True

# Parameters for the dataset class
dataset:

  # Path to the root of the dataset; detects which path to use based on device
  root: "/mnt/d/Datasets/coco" # windows path
  root_mac: "/Users/bsele/datasets/coco" # mac path

  # Number of CPU processes the next sample in the dataset; use 0 to only use the main process
  num_workers: 4

test:

  batch_size: 4

  # Abs path of checkpoint file (.pt) to evaluate on; 
  checkpoint_path: /Users/bsele/programming/detectors/output/train/development/2024_12_27-08_22_44_AM/checkpoints/best_mAP_0-84.pt
# GPU parameters
cuda:

  # List of GPU devices to use
  gpus: [0]


# Reproducibility information
reproducibility:
  seed: 42
