# Base config file which stores the default parameters which apply to all model configurations
---

# Mode to use for debugging/development; this only uses a few samples in in the train/val dataset
# to quickly run the code
debug_mode: False

# Root directory of your project; type "pwd" in the command line to find it
root_dir: "/home/bselee/programming/detectors"

# Path to the trained models state dict;
state_dict_path: "/home/bselee/programming/detectors/output/development/2024_09_01-10_39_10_AM/checkpoint0010"

# Base directory for output files; do not change this 
output_path: "output/test"

# Experiment name; this will be used for the output directory; use "development" when developing
exp_name: "development"

# Name of dataset; must be one of the names in the dataset_map dict
dataset_name: "CocoDetectionMiniTrain"

# Parameters for the dataset class
dataset:

  # Path to the root of the dataset
  root: "/mnt/c/Users/bsele/Documents/Datasets/coco_minitrain_25k"

  # Number of CPU processes the next sample in the dataset; use 0 to only use the main process
  num_workers: 4

# GPU parameters
cuda:

  # List of GPU devices to use
  gpus: [0]

# Logging parameters
logging:

  # Log the train progress every n steps
  train_steps_freq: 20

# Reproducibility information
reproducibility:
  seed: 42
