# Base config file which stores the default parameters which apply to all model configurations
---
# path to additional configuration files to load and merge into a single configuration dictionary; 
# these are required
__include__:
  # use the relative path from the project root
  dataset_config: configs/datasets/coco-2017.yaml
  model_config: configs/rt-detrv2/rtdetrv2-rn50-model.yaml

# Base directory for output files
output_dir: "output"

# # Experiment name; this will be used for the output directory; use "development" when developing
# exp_name: "rtdetrv2-inference"

# Path to the trained model; e.g., if using ONNX runtime this should be a .onnx file, if using torch this be a .pt file
trained_model_path: /home/bselee/programming/detectors/output/onnx/rtdetrv2/rtdetrv2.onnx

images_dir: "/mnt/d/datasets/coco/images/test2017"
viz_n_images: 10

transforms:
  transforms:
    - {type: Resize, params: {size: [640, 640]}}
    - {type: Normalize, params: {mean: [0.0, 0.0, 0.0], std: [1.0, 1.0, 1.0], out_bbox_format: "cxcywh"}}

# GPU parameters
cuda:
  # List of GPU devices to use
  gpus: [1]

  # the communications library to use for distributed training; default for cuda should be 
  # "nccl" prounounced "nickel"
  backend: "nccl"