# Base config file which stores the default parameters which apply to all model configurations
---

# Whether to run in development/debugging mode; this only uses a few samples in in the train/val dataset
# to quickly run the code as well as sets num_workers=0
dev_mode: True

# NOTE: output dir is derived from the checkpoint path so we can keep full experiment runs in the
#       the same dir

# Name of dataset; must be one of the names in the dataset_map dict
dataset_name: "CocoDetection"

visualize:
  # Whether to plot the predicted bounding boxes on the test set; if False only the AP scores are shown
  plot_detections: True

  # confidence threshold to filter predictions by; without this, we would have `num_select` detections
  # per image and end up plotting many low confidence boxes
  conf_threshold: 0.5

  # number of images to plot detections on
  plot_n_images: 50


# Parameters for the dataset class
dataset:
  # Path to the root of the dataset; detects which path to use based on device
  root: "/mnt/d/Datasets/coco" # windows path
  root_mac: "/Users/bsele/datasets/coco" # mac path

  # max_class_id + 1 in the coco file; see data.coco_ds.CocoDetection.num_classes for more info;
  # NOTE: the max_id of the "categories" key in the coco annotation file is 90 (so 90 + 1 = 91)
  num_classes: 91

  # Number of CPU processes the next sample in the dataset; use 0 to only use the main process
  num_workers: 0

test:
  # Right now this can't be controlled because there's no batch sampler implemented;
  # mAP slightly decreased when batched due to padding
  batch_size: 1

  # Abs path of checkpoint file (.pt) to evaluate on; 
  checkpoint_path: /home/bselee/programming/detectors/output/train/resnet50-dino/2025_08_16-11_44_38_PM/checkpoints/best_mAP_46-59.pt

cuda:
  # List of GPU devices to use
  gpus: [0]

# Reproducibility information
reproducibility:
  seed: 42
